name: NoVoid
main: LeronDoesGM\NoVoid\Main
version: 1.0.0
author: [LeronDoesGM]
api: ['3.0.0-ALPHA6']
load: POSTWORLD

commands:
 nv:
  description: NoVoid Commands
  usage: "Usage: /nv"
  permission: novoid.command.nv
 heart:
  description: NoVoid Commands
  usage: "Usage: /heart <Amount>"
  permission: novoid.command.nv
permissions:
 novoid.command.nv:
  description: "Allows the user to run novoid command"
  default: op